// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: theater.sql

package sqlc

import (
	"context"
	"time"
)

const countTheater = `-- name: CountTheater :one
SELECT COUNT(*) as total
FROM theaters
WHERE anime_id = ?
`

func (q *Queries) CountTheater(ctx context.Context, animeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTheater, animeID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTheater = `-- name: CreateTheater :one
INSERT INTO theaters (
    anime_id,
    name,
    cover,
    released_at,
    description,
    status
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, anime_id, name, cover, released_at, description, status, created_at, updated_at
`

type CreateTheaterParams struct {
	AnimeID     int64     `json:"anime_id"`
	Name        string    `json:"name"`
	Cover       string    `json:"cover"`
	ReleasedAt  time.Time `json:"released_at"`
	Description string    `json:"description"`
	Status      int64     `json:"status"`
}

func (q *Queries) CreateTheater(ctx context.Context, arg CreateTheaterParams) (Theater, error) {
	row := q.db.QueryRowContext(ctx, createTheater,
		arg.AnimeID,
		arg.Name,
		arg.Cover,
		arg.ReleasedAt,
		arg.Description,
		arg.Status,
	)
	var i Theater
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.Name,
		&i.Cover,
		&i.ReleasedAt,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTheater = `-- name: DeleteTheater :exec
DELETE FROM theaters
WHERE id = ?
`

func (q *Queries) DeleteTheater(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTheater, id)
	return err
}

const getTheater = `-- name: GetTheater :one
SELECT id, anime_id, name, cover, released_at, description, status, created_at, updated_at FROM theaters
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTheater(ctx context.Context, id int64) (Theater, error) {
	row := q.db.QueryRowContext(ctx, getTheater, id)
	var i Theater
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.Name,
		&i.Cover,
		&i.ReleasedAt,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTheater = `-- name: ListTheater :many
SELECT id, anime_id, name, cover, released_at, description, status, created_at, updated_at FROM theaters
WHERE anime_id = ?
ORDER BY id
LIMIT ?
OFFSET ?
`

type ListTheaterParams struct {
	AnimeID int64 `json:"anime_id"`
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
}

func (q *Queries) ListTheater(ctx context.Context, arg ListTheaterParams) ([]Theater, error) {
	rows, err := q.db.QueryContext(ctx, listTheater, arg.AnimeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theater{}
	for rows.Next() {
		var i Theater
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.Name,
			&i.Cover,
			&i.ReleasedAt,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTheater = `-- name: UpdateTheater :one
UPDATE theaters
SET name = ?, cover = ?, released_at = ?, description = ?, status = ?
WHERE id = ?
RETURNING id, anime_id, name, cover, released_at, description, status, created_at, updated_at
`

type UpdateTheaterParams struct {
	Name        string    `json:"name"`
	Cover       string    `json:"cover"`
	ReleasedAt  time.Time `json:"released_at"`
	Description string    `json:"description"`
	Status      int64     `json:"status"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateTheater(ctx context.Context, arg UpdateTheaterParams) (Theater, error) {
	row := q.db.QueryRowContext(ctx, updateTheater,
		arg.Name,
		arg.Cover,
		arg.ReleasedAt,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Theater
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.Name,
		&i.Cover,
		&i.ReleasedAt,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
