// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnimesColumns holds the columns for the "animes" table.
	AnimesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AnimesTable holds the schema information for the "animes" table.
	AnimesTable = &schema.Table{
		Name:       "animes",
		Columns:    AnimesColumns,
		PrimaryKey: []*schema.Column{AnimesColumns[0]},
	}
	// EpisodesColumns holds the columns for the "episodes" table.
	EpisodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "value", Type: field.TypeInt64},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "season_episodes", Type: field.TypeInt, Nullable: true},
	}
	// EpisodesTable holds the schema information for the "episodes" table.
	EpisodesTable = &schema.Table{
		Name:       "episodes",
		Columns:    EpisodesColumns,
		PrimaryKey: []*schema.Column{EpisodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "episodes_seasons_episodes",
				Columns:    []*schema.Column{EpisodesColumns[6]},
				RefColumns: []*schema.Column{SeasonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SeasonsColumns holds the columns for the "seasons" table.
	SeasonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "value", Type: field.TypeInt64},
		{Name: "cover", Type: field.TypeString},
		{Name: "released_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "anime_seasons", Type: field.TypeInt, Nullable: true},
	}
	// SeasonsTable holds the schema information for the "seasons" table.
	SeasonsTable = &schema.Table{
		Name:       "seasons",
		Columns:    SeasonsColumns,
		PrimaryKey: []*schema.Column{SeasonsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "seasons_animes_seasons",
				Columns:    []*schema.Column{SeasonsColumns[8]},
				RefColumns: []*schema.Column{AnimesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TheatersColumns holds the columns for the "theaters" table.
	TheatersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "cover", Type: field.TypeString},
		{Name: "released_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "anime_theaters", Type: field.TypeInt, Nullable: true},
	}
	// TheatersTable holds the schema information for the "theaters" table.
	TheatersTable = &schema.Table{
		Name:       "theaters",
		Columns:    TheatersColumns,
		PrimaryKey: []*schema.Column{TheatersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "theaters_animes_theaters",
				Columns:    []*schema.Column{TheatersColumns[7]},
				RefColumns: []*schema.Column{AnimesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnimesTable,
		EpisodesTable,
		SeasonsTable,
		TheatersTable,
	}
)

func init() {
	EpisodesTable.ForeignKeys[0].RefTable = SeasonsTable
	SeasonsTable.ForeignKeys[0].RefTable = AnimesTable
	TheatersTable.ForeignKeys[0].RefTable = AnimesTable
}
