// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dongwlin/anime-list/internal/ent/anime"
)

// Anime is the model entity for the Anime schema.
type Anime struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnimeQuery when eager-loading is set.
	Edges        AnimeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnimeEdges holds the relations/edges for other nodes in the graph.
type AnimeEdges struct {
	// Seasons holds the value of the seasons edge.
	Seasons []*Season `json:"seasons,omitempty"`
	// Theaters holds the value of the theaters edge.
	Theaters []*Theater `json:"theaters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SeasonsOrErr returns the Seasons value or an error if the edge
// was not loaded in eager-loading.
func (e AnimeEdges) SeasonsOrErr() ([]*Season, error) {
	if e.loadedTypes[0] {
		return e.Seasons, nil
	}
	return nil, &NotLoadedError{edge: "seasons"}
}

// TheatersOrErr returns the Theaters value or an error if the edge
// was not loaded in eager-loading.
func (e AnimeEdges) TheatersOrErr() ([]*Theater, error) {
	if e.loadedTypes[1] {
		return e.Theaters, nil
	}
	return nil, &NotLoadedError{edge: "theaters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Anime) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case anime.FieldID, anime.FieldStatus:
			values[i] = new(sql.NullInt64)
		case anime.FieldName, anime.FieldDescription:
			values[i] = new(sql.NullString)
		case anime.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Anime fields.
func (a *Anime) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case anime.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case anime.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case anime.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				a.Description = value.String
			}
		case anime.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				a.Status = int(value.Int64)
			}
		case anime.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Anime.
// This includes values selected through modifiers, order, etc.
func (a *Anime) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QuerySeasons queries the "seasons" edge of the Anime entity.
func (a *Anime) QuerySeasons() *SeasonQuery {
	return NewAnimeClient(a.config).QuerySeasons(a)
}

// QueryTheaters queries the "theaters" edge of the Anime entity.
func (a *Anime) QueryTheaters() *TheaterQuery {
	return NewAnimeClient(a.config).QueryTheaters(a)
}

// Update returns a builder for updating this Anime.
// Note that you need to call Anime.Unwrap() before calling this method if this Anime
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Anime) Update() *AnimeUpdateOne {
	return NewAnimeClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Anime entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Anime) Unwrap() *Anime {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Anime is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Anime) String() string {
	var builder strings.Builder
	builder.WriteString("Anime(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(a.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", a.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Animes is a parsable slice of Anime.
type Animes []*Anime
