// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dongwlin/anime-list/internal/ent/anime"
	"github.com/dongwlin/anime-list/internal/ent/season"
	"github.com/dongwlin/anime-list/internal/ent/theater"
)

// AnimeCreate is the builder for creating a Anime entity.
type AnimeCreate struct {
	config
	mutation *AnimeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AnimeCreate) SetName(s string) *AnimeCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetDescription sets the "description" field.
func (ac *AnimeCreate) SetDescription(s string) *AnimeCreate {
	ac.mutation.SetDescription(s)
	return ac
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ac *AnimeCreate) SetNillableDescription(s *string) *AnimeCreate {
	if s != nil {
		ac.SetDescription(*s)
	}
	return ac
}

// SetStatus sets the "status" field.
func (ac *AnimeCreate) SetStatus(i int) *AnimeCreate {
	ac.mutation.SetStatus(i)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AnimeCreate) SetNillableStatus(i *int) *AnimeCreate {
	if i != nil {
		ac.SetStatus(*i)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AnimeCreate) SetCreatedAt(t time.Time) *AnimeCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AnimeCreate) SetNillableCreatedAt(t *time.Time) *AnimeCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// AddSeasonIDs adds the "seasons" edge to the Season entity by IDs.
func (ac *AnimeCreate) AddSeasonIDs(ids ...int) *AnimeCreate {
	ac.mutation.AddSeasonIDs(ids...)
	return ac
}

// AddSeasons adds the "seasons" edges to the Season entity.
func (ac *AnimeCreate) AddSeasons(s ...*Season) *AnimeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ac.AddSeasonIDs(ids...)
}

// AddTheaterIDs adds the "theaters" edge to the Theater entity by IDs.
func (ac *AnimeCreate) AddTheaterIDs(ids ...int) *AnimeCreate {
	ac.mutation.AddTheaterIDs(ids...)
	return ac
}

// AddTheaters adds the "theaters" edges to the Theater entity.
func (ac *AnimeCreate) AddTheaters(t ...*Theater) *AnimeCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTheaterIDs(ids...)
}

// Mutation returns the AnimeMutation object of the builder.
func (ac *AnimeCreate) Mutation() *AnimeMutation {
	return ac.mutation
}

// Save creates the Anime in the database.
func (ac *AnimeCreate) Save(ctx context.Context) (*Anime, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AnimeCreate) SaveX(ctx context.Context) *Anime {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AnimeCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AnimeCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AnimeCreate) defaults() {
	if _, ok := ac.mutation.Description(); !ok {
		v := anime.DefaultDescription
		ac.mutation.SetDescription(v)
	}
	if _, ok := ac.mutation.Status(); !ok {
		v := anime.DefaultStatus
		ac.mutation.SetStatus(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := anime.DefaultCreatedAt
		ac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AnimeCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Anime.name"`)}
	}
	if _, ok := ac.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Anime.description"`)}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Anime.status"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Anime.created_at"`)}
	}
	return nil
}

func (ac *AnimeCreate) sqlSave(ctx context.Context) (*Anime, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AnimeCreate) createSpec() (*Anime, *sqlgraph.CreateSpec) {
	var (
		_node = &Anime{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(anime.Table, sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(anime.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.Description(); ok {
		_spec.SetField(anime.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(anime.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(anime.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ac.mutation.SeasonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   anime.SeasonsTable,
			Columns: []string{anime.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TheatersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   anime.TheatersTable,
			Columns: []string{anime.TheatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(theater.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnimeCreateBulk is the builder for creating many Anime entities in bulk.
type AnimeCreateBulk struct {
	config
	err      error
	builders []*AnimeCreate
}

// Save creates the Anime entities in the database.
func (acb *AnimeCreateBulk) Save(ctx context.Context) ([]*Anime, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Anime, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnimeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AnimeCreateBulk) SaveX(ctx context.Context) []*Anime {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AnimeCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AnimeCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
