// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dongwlin/anime-list/internal/ent/anime"
	"github.com/dongwlin/anime-list/internal/ent/episode"
	"github.com/dongwlin/anime-list/internal/ent/schema"
	"github.com/dongwlin/anime-list/internal/ent/season"
	"github.com/dongwlin/anime-list/internal/ent/theater"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	animeFields := schema.Anime{}.Fields()
	_ = animeFields
	// animeDescDescription is the schema descriptor for description field.
	animeDescDescription := animeFields[1].Descriptor()
	// anime.DefaultDescription holds the default value on creation for the description field.
	anime.DefaultDescription = animeDescDescription.Default.(string)
	// animeDescStatus is the schema descriptor for status field.
	animeDescStatus := animeFields[2].Descriptor()
	// anime.DefaultStatus holds the default value on creation for the status field.
	anime.DefaultStatus = animeDescStatus.Default.(int)
	// animeDescCreatedAt is the schema descriptor for created_at field.
	animeDescCreatedAt := animeFields[3].Descriptor()
	// anime.DefaultCreatedAt holds the default value on creation for the created_at field.
	anime.DefaultCreatedAt = animeDescCreatedAt.Default.(time.Time)
	episodeFields := schema.Episode{}.Fields()
	_ = episodeFields
	// episodeDescDescription is the schema descriptor for description field.
	episodeDescDescription := episodeFields[2].Descriptor()
	// episode.DefaultDescription holds the default value on creation for the description field.
	episode.DefaultDescription = episodeDescDescription.Default.(string)
	// episodeDescStatus is the schema descriptor for status field.
	episodeDescStatus := episodeFields[3].Descriptor()
	// episode.DefaultStatus holds the default value on creation for the status field.
	episode.DefaultStatus = episodeDescStatus.Default.(int)
	// episodeDescCreatedAt is the schema descriptor for created_at field.
	episodeDescCreatedAt := episodeFields[4].Descriptor()
	// episode.DefaultCreatedAt holds the default value on creation for the created_at field.
	episode.DefaultCreatedAt = episodeDescCreatedAt.Default.(time.Time)
	seasonFields := schema.Season{}.Fields()
	_ = seasonFields
	// seasonDescDescription is the schema descriptor for description field.
	seasonDescDescription := seasonFields[4].Descriptor()
	// season.DefaultDescription holds the default value on creation for the description field.
	season.DefaultDescription = seasonDescDescription.Default.(string)
	// seasonDescStatus is the schema descriptor for status field.
	seasonDescStatus := seasonFields[5].Descriptor()
	// season.DefaultStatus holds the default value on creation for the status field.
	season.DefaultStatus = seasonDescStatus.Default.(int)
	// seasonDescCreatedAt is the schema descriptor for created_at field.
	seasonDescCreatedAt := seasonFields[6].Descriptor()
	// season.DefaultCreatedAt holds the default value on creation for the created_at field.
	season.DefaultCreatedAt = seasonDescCreatedAt.Default.(time.Time)
	theaterFields := schema.Theater{}.Fields()
	_ = theaterFields
	// theaterDescReleasedAt is the schema descriptor for released_at field.
	theaterDescReleasedAt := theaterFields[2].Descriptor()
	// theater.DefaultReleasedAt holds the default value on creation for the released_at field.
	theater.DefaultReleasedAt = theaterDescReleasedAt.Default.(time.Time)
	// theaterDescDescription is the schema descriptor for description field.
	theaterDescDescription := theaterFields[3].Descriptor()
	// theater.DefaultDescription holds the default value on creation for the description field.
	theater.DefaultDescription = theaterDescDescription.Default.(string)
	// theaterDescStatus is the schema descriptor for status field.
	theaterDescStatus := theaterFields[4].Descriptor()
	// theater.DefaultStatus holds the default value on creation for the status field.
	theater.DefaultStatus = theaterDescStatus.Default.(int)
	// theaterDescCreatedAt is the schema descriptor for created_at field.
	theaterDescCreatedAt := theaterFields[5].Descriptor()
	// theater.DefaultCreatedAt holds the default value on creation for the created_at field.
	theater.DefaultCreatedAt = theaterDescCreatedAt.Default.(time.Time)
}
