// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dongwlin/anime-list/internal/ent/anime"
	"github.com/dongwlin/anime-list/internal/ent/theater"
)

// Theater is the model entity for the Theater schema.
type Theater struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover string `json:"cover,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt time.Time `json:"released_at,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TheaterQuery when eager-loading is set.
	Edges          TheaterEdges `json:"edges"`
	anime_theaters *int
	selectValues   sql.SelectValues
}

// TheaterEdges holds the relations/edges for other nodes in the graph.
type TheaterEdges struct {
	// Anime holds the value of the anime edge.
	Anime *Anime `json:"anime,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AnimeOrErr returns the Anime value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TheaterEdges) AnimeOrErr() (*Anime, error) {
	if e.Anime != nil {
		return e.Anime, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: anime.Label}
	}
	return nil, &NotLoadedError{edge: "anime"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Theater) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case theater.FieldID, theater.FieldStatus:
			values[i] = new(sql.NullInt64)
		case theater.FieldName, theater.FieldCover, theater.FieldDescription:
			values[i] = new(sql.NullString)
		case theater.FieldReleasedAt, theater.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case theater.ForeignKeys[0]: // anime_theaters
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Theater fields.
func (t *Theater) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case theater.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case theater.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				t.Name = value.String
			}
		case theater.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				t.Cover = value.String
			}
		case theater.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				t.ReleasedAt = value.Time
			}
		case theater.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				t.Description = value.String
			}
		case theater.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				t.Status = int(value.Int64)
			}
		case theater.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case theater.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field anime_theaters", value)
			} else if value.Valid {
				t.anime_theaters = new(int)
				*t.anime_theaters = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Theater.
// This includes values selected through modifiers, order, etc.
func (t *Theater) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryAnime queries the "anime" edge of the Theater entity.
func (t *Theater) QueryAnime() *AnimeQuery {
	return NewTheaterClient(t.config).QueryAnime(t)
}

// Update returns a builder for updating this Theater.
// Note that you need to call Theater.Unwrap() before calling this method if this Theater
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Theater) Update() *TheaterUpdateOne {
	return NewTheaterClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Theater entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Theater) Unwrap() *Theater {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Theater is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Theater) String() string {
	var builder strings.Builder
	builder.WriteString("Theater(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("name=")
	builder.WriteString(t.Name)
	builder.WriteString(", ")
	builder.WriteString("cover=")
	builder.WriteString(t.Cover)
	builder.WriteString(", ")
	builder.WriteString("released_at=")
	builder.WriteString(t.ReleasedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(t.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", t.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Theaters is a parsable slice of Theater.
type Theaters []*Theater
