// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dongwlin/anime-list/internal/ent/anime"
	"github.com/dongwlin/anime-list/internal/ent/predicate"
	"github.com/dongwlin/anime-list/internal/ent/theater"
)

// TheaterQuery is the builder for querying Theater entities.
type TheaterQuery struct {
	config
	ctx        *QueryContext
	order      []theater.OrderOption
	inters     []Interceptor
	predicates []predicate.Theater
	withAnime  *AnimeQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TheaterQuery builder.
func (tq *TheaterQuery) Where(ps ...predicate.Theater) *TheaterQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TheaterQuery) Limit(limit int) *TheaterQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TheaterQuery) Offset(offset int) *TheaterQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TheaterQuery) Unique(unique bool) *TheaterQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TheaterQuery) Order(o ...theater.OrderOption) *TheaterQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryAnime chains the current query on the "anime" edge.
func (tq *TheaterQuery) QueryAnime() *AnimeQuery {
	query := (&AnimeClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(theater.Table, theater.FieldID, selector),
			sqlgraph.To(anime.Table, anime.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, theater.AnimeTable, theater.AnimeColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Theater entity from the query.
// Returns a *NotFoundError when no Theater was found.
func (tq *TheaterQuery) First(ctx context.Context) (*Theater, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{theater.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TheaterQuery) FirstX(ctx context.Context) *Theater {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Theater ID from the query.
// Returns a *NotFoundError when no Theater ID was found.
func (tq *TheaterQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{theater.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TheaterQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Theater entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Theater entity is found.
// Returns a *NotFoundError when no Theater entities are found.
func (tq *TheaterQuery) Only(ctx context.Context) (*Theater, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{theater.Label}
	default:
		return nil, &NotSingularError{theater.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TheaterQuery) OnlyX(ctx context.Context) *Theater {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Theater ID in the query.
// Returns a *NotSingularError when more than one Theater ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TheaterQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{theater.Label}
	default:
		err = &NotSingularError{theater.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TheaterQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Theaters.
func (tq *TheaterQuery) All(ctx context.Context) ([]*Theater, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryAll)
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Theater, *TheaterQuery]()
	return withInterceptors[[]*Theater](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TheaterQuery) AllX(ctx context.Context) []*Theater {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Theater IDs.
func (tq *TheaterQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryIDs)
	if err = tq.Select(theater.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TheaterQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TheaterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryCount)
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TheaterQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TheaterQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TheaterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryExist)
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TheaterQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TheaterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TheaterQuery) Clone() *TheaterQuery {
	if tq == nil {
		return nil
	}
	return &TheaterQuery{
		config:     tq.config,
		ctx:        tq.ctx.Clone(),
		order:      append([]theater.OrderOption{}, tq.order...),
		inters:     append([]Interceptor{}, tq.inters...),
		predicates: append([]predicate.Theater{}, tq.predicates...),
		withAnime:  tq.withAnime.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithAnime tells the query-builder to eager-load the nodes that are connected to
// the "anime" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TheaterQuery) WithAnime(opts ...func(*AnimeQuery)) *TheaterQuery {
	query := (&AnimeClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withAnime = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Theater.Query().
//		GroupBy(theater.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TheaterQuery) GroupBy(field string, fields ...string) *TheaterGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TheaterGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = theater.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Theater.Query().
//		Select(theater.FieldName).
//		Scan(ctx, &v)
func (tq *TheaterQuery) Select(fields ...string) *TheaterSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TheaterSelect{TheaterQuery: tq}
	sbuild.label = theater.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TheaterSelect configured with the given aggregations.
func (tq *TheaterQuery) Aggregate(fns ...AggregateFunc) *TheaterSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TheaterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !theater.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TheaterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Theater, error) {
	var (
		nodes       = []*Theater{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [1]bool{
			tq.withAnime != nil,
		}
	)
	if tq.withAnime != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, theater.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Theater).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Theater{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withAnime; query != nil {
		if err := tq.loadAnime(ctx, query, nodes, nil,
			func(n *Theater, e *Anime) { n.Edges.Anime = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TheaterQuery) loadAnime(ctx context.Context, query *AnimeQuery, nodes []*Theater, init func(*Theater), assign func(*Theater, *Anime)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Theater)
	for i := range nodes {
		if nodes[i].anime_theaters == nil {
			continue
		}
		fk := *nodes[i].anime_theaters
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(anime.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "anime_theaters" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TheaterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TheaterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(theater.Table, theater.Columns, sqlgraph.NewFieldSpec(theater.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theater.FieldID)
		for i := range fields {
			if fields[i] != theater.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TheaterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(theater.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = theater.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TheaterGroupBy is the group-by builder for Theater entities.
type TheaterGroupBy struct {
	selector
	build *TheaterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TheaterGroupBy) Aggregate(fns ...AggregateFunc) *TheaterGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TheaterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, ent.OpQueryGroupBy)
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TheaterQuery, *TheaterGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TheaterGroupBy) sqlScan(ctx context.Context, root *TheaterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TheaterSelect is the builder for selecting fields of Theater entities.
type TheaterSelect struct {
	*TheaterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TheaterSelect) Aggregate(fns ...AggregateFunc) *TheaterSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TheaterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, ent.OpQuerySelect)
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TheaterQuery, *TheaterSelect](ctx, ts.TheaterQuery, ts, ts.inters, v)
}

func (ts *TheaterSelect) sqlScan(ctx context.Context, root *TheaterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
