// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Anime is the predicate function for anime builders.
type Anime func(*sql.Selector)

// Episode is the predicate function for episode builders.
type Episode func(*sql.Selector)

// Season is the predicate function for season builders.
type Season func(*sql.Selector)

// Theater is the predicate function for theater builders.
type Theater func(*sql.Selector)
