// Code generated by ent, DO NOT EDIT.

package theater

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the theater type in the database.
	Label = "theater"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldReleasedAt holds the string denoting the released_at field in the database.
	FieldReleasedAt = "released_at"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAnime holds the string denoting the anime edge name in mutations.
	EdgeAnime = "anime"
	// Table holds the table name of the theater in the database.
	Table = "theaters"
	// AnimeTable is the table that holds the anime relation/edge.
	AnimeTable = "theaters"
	// AnimeInverseTable is the table name for the Anime entity.
	// It exists in this package in order to avoid circular dependency with the "anime" package.
	AnimeInverseTable = "animes"
	// AnimeColumn is the table column denoting the anime relation/edge.
	AnimeColumn = "anime_theaters"
)

// Columns holds all SQL columns for theater fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCover,
	FieldReleasedAt,
	FieldDescription,
	FieldStatus,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "theaters"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"anime_theaters",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReleasedAt holds the default value on creation for the "released_at" field.
	DefaultReleasedAt time.Time
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
)

// OrderOption defines the ordering options for the Theater queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByReleasedAt orders the results by the released_at field.
func ByReleasedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleasedAt, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAnimeField orders the results by anime field.
func ByAnimeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnimeStep(), sql.OrderByField(field, opts...))
	}
}
func newAnimeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnimeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AnimeTable, AnimeColumn),
	)
}
