// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"database/sql"
	"github.com/dongwlin/anime-list/internal/handler"
	"github.com/dongwlin/anime-list/internal/server"
	"github.com/dongwlin/anime-list/internal/store"
	"github.com/google/wire"
)

// Injectors from wire.go:

func newServer() *server.HttpServer {
	db := connDB()
	storeStore := store.NewStore(db)
	handlerHandler := handler.NewHandler(storeStore)
	pingHandler := handler.NewPingHandler(handlerHandler)
	animeHandler := handler.NewAnimeHandler(handlerHandler)
	seasonHandler := handler.NewSeasonHandler(handlerHandler)
	episodeHandler := handler.NewEpisodeHandler(handlerHandler)
	theaterHandler := handler.NewTheaterHandler(handlerHandler)
	httpServer := server.NewHttpServer(pingHandler, animeHandler, seasonHandler, episodeHandler, theaterHandler)
	return httpServer
}

// wire.go:

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewPingHandler, handler.NewAnimeHandler, handler.NewSeasonHandler, handler.NewEpisodeHandler, handler.NewTheaterHandler)

func connDB() *sql.DB {
	conn, err := sql.Open("sqlite3", "./data.db")
	if err != nil {
		panic(err)
	}
	return conn
}
